---
- name: install apache
  apt: name=apache2 state=present
- name: Setup the virtual host
  template:
    src=drupal.vhost.conf.j2
    dest=/etc/apache2/sites-available/{{ ProjectName }}.conf
- name: Remove default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache
- name: Enable the rewrite module
  file:
    src=/etc/apache2/mods-available/rewrite.load
    dest=/etc/apache2/mods-enabled/rewrite.load
    state=link
  notify:
    - reload apache
- name: Enable new vagrant virtual host
  file:
    src=/etc/apache2/sites-available/{{ ProjectName }}.conf
    dest=/etc/apache2/sites-enabled/{{ ProjectName }}.conf
    state=link
  notify:
    - reload apache
- name: Set group permissions to {{ ApacheRoot }}
  file:
    path: "{{ ApacheRoot }}"
    owner: root
    group: www-data
    mode: 02775
- name: adding existing user ubuntu to group www-data
  user:
    name: ubuntu
    groups: www-data
    append: yes
