- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: set rights for composer
  file:
    path: /usr/local/bin/composer
    owner: ubuntu
    group: ubuntu
    mode: 0775

# - name: composer install project
#   composer:
#     command: install
#     working_dir: "{{ ApacheWorkingDir }}"
#
#
- name: add {{ VendorBinPath }} to PATH
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{VendorBinPath}}).*?)(["]*)$'
    line="PATH=\1\2:{{VendorBinPath}}\3"
