- name: Create Composer Project for
  shell: >
    composer create-project drupal-composer/drupal-project:8.x-dev {{ ProjectName }} --stability dev --no-interaction
  args:
    chdir: "{{ ApacheRoot }}"
