- name: Create Composer Project
  become: yes
  become_user: ubuntu
  register: composerrun
  command: >
    composer create-project drupal-composer/drupal-project:8.x-dev {{ ProjectName }} --stability dev --no-interaction
  args:
    chdir: "{{ ApacheRoot }}"
    creates: "{{ ApacheDocumentRoot }}"


- name: Install {{ ProjectName }} using Drupal Console
  become: yes
  become_user: ubuntu
  command: >
    drupal site:install  standard  \
      --langcode="en"  \
      --db-type="mysql"  \
      --db-host="127.0.0.1"  \
      --db-name="drupal"  \
      --db-user="drupal"  \
      --db-pass="geheim"  \
      --db-port="3306"  \
      --db-prefix="" \
      --site-name="Drupal 8"  \
      --site-mail="admin@example.com"  \
      --account-name="admin"  \
      --account-mail="admin@example.com"  \
      --account-pass="p455w0rd"
  args:
    chdir: "{{ ApacheDocumentRoot }}/web"
