- name: Create Composer Project
  become: yes
  become_user: ubuntu
  register: composerrun
  command: >
    composer create-project drupal-composer/drupal-project:8.x-dev {{ ProjectName }} --stability dev --no-interaction
  args:
    chdir: "{{ ApacheRoot }}"
    creates: "{{ ApacheDocumentRoot }}"

- name: Handle failed composer install
  when: composerrun | failed
  file:
    state: absent
    path: "{{ ApacheDocumentRoot }}"

# - debug:
#     msg: "variable is {{ composerrun }} {{ composerrun.changed }}"

- name: Install {{ ProjectName }} using Drupal Console
  become: yes
  become_user: ubuntu
  when: composerrun.changed
  command: >
    drupal site:install  standard  \
      --langcode="en"  \
      --db-type="mysql"  \
      --db-host="127.0.0.1"  \
      --db-name="{{ MySqlDatabaseName }}"  \
      --db-user="{{ MySqlDatabaseUser }}"  \
      --db-pass="{{ MySqlDatabasePassword }}"  \
      --db-prefix="{{ DrupalDbPrefix }}" \
      --site-name="{{ DrupalSiteName }}"  \
      --site-mail="{{ DrupalSiteMail }}"  \
      --account-name="{{ DrupalAdminName }}"  \
      --account-mail="{{ DrupalAdminEmail }}"  \
      --account-pass="{{ DrupalAdminPassword }}"
  args:
    chdir: "{{ ApacheDocumentRoot }}/web"
  notify:
    - reload apache
