- name: Create Composer Project
  become: yes
  become_user: ubuntu
  register: composerrun
  command: >
    composer create-project drupal-composer/drupal-project:8.x-dev {{ ProjectName }} --stability dev --no-interaction
  args:
    chdir: "{{ ApacheRoot }}"
    creates: "{{ ApacheDocumentRoot }}"

- debug:
    msg: "variable is {{ composerrun }} {{ composerrun.changed }}"

- name: Install {{ ProjectName }} using Drupal Console
  become: yes
  become_user: ubuntu
  when: composerrun.changed
  command: >
    drupal site:install  standard  \
      --langcode="en"  \
      --db-type="mysql"  \
      --db-host="127.0.0.1"  \
      --db-name="{{ MySqlDatabaseName }}"  \
      --db-user="{{ MySqlDatabaseUser }}"  \
      --db-pass="{{ MySqlDatabasePassword }}"  \
      --db-prefix="" \
      --site-name="Drupal 8"  \
      --site-mail="admin@example.com"  \
      --account-name="admin"  \
      --account-mail="admin@example.com"  \
      --account-pass="p455w0rd"
  args:
    chdir: "{{ ApacheDocumentRoot }}/web"
