- name: Create Composer Project for
  become: yes
  become_user: ubuntu
  shell: >
    composer create-project drupal-composer/drupal-project:8.x-dev mastering --stability dev --no-interaction
  args:
    chdir: "{{ ApacheRoot }}"
