---
- name: install php
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - php7.0
    - mcrypt
    - php7.0-curl
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-soap
    - php7.0-xml
    - php7.0-zip
    - libapache2-mod-php7.0
    - php-xdebug
  notify:
    - reload apache

- name: Set the php.ini
  template:
        src=php.ini.j2
        dest=/etc/php/7.0/apache2/php.ini
  notify:
    - reload apache

- name: Set the xdebug config
  template:
        src=20-xdebug.ini.j2
        dest=/etc/php/7.0/apache2/conf.d/20-xdebug.ini
  notify:
    - reload apache
