---
- name: install php
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - php
    - mcrypt
    - php-curl
    - php-gd
    - php-mbstring
    - php-mysql
    - php-soap
    - php-xml
    - php-zip
    - libapache2-mod-php
    - php-xdebug
  notify:
    - reload apache

- name: Set the php.ini file
  template:
        src=php.ini.j2
        dest=/etc/php/7.2/apache2/php.ini
  notify:
    - reload apache

- name: Enable xdebug
  template:
        src=20-xdebug.ini.j2
        dest=/etc/php/7.2/apache2/conf.d/20-xdebug.ini
  notify:
    - reload apache
