---
- name: install php
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - php7.0
    - mcrypt
    - php7.0-curl
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-xml
    - php7.0-zip
    - libapache2-mod-php7.0
  notify:
    - reload apache
