---
- name: Setup TYPO3 {{ ApacheDocumentRoot }}/typo3conf/LocalConfiguration.php

  command: >
    /var/www/html/vendor/bin/typo3cms install:setup
      --non-interactive
      --database-user-name {{ MySqlDatabaseUser }}
      --database-user-password {{ MySqlDatabasePassword }}
      --database-host-name localhost
      --database-name {{ MySqlDatabaseName }}
      --use-existing-database {{ MySqlDatabaseName }}
      --admin-user-name {{ TYPO3AdminUsername }}
      --admin-password {{ TYPO3AdminPassword }}
      --site-name {{ TYPO3SiteName }}
  args:
    creates: "{{ ApacheDocumentRoot }}/typo3conf/LocalConfiguration.php"

- name: Remove Database Infos from LocalConfiguration.php"
  command: >
    /var/www/html/vendor/bin/typo3cms configuration:remove DB
    --force

- name: Write the dotenv
  template:
    src=typo3-vagrant.env.j2
    dest={{ApacheWorkingDir}}/.env

- name: Write the Additional-Configuration
  template:
    src=AdditionalConfiguration.php.j2
    dest={{ApacheWorkingDir}}/typo3conf/AdditionalConfiguration.php
