---
- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySqlRootPassword | quote}}' vtype='password'

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySqlRootPassword | quote}}' vtype='password'

- name: install MySQL
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
    - makepasswd

- name: Create MySQL DB
  mysql_db: encoding=utf8 name={{ MySqlDatabaseName }} login_password="{{MySqlRootPassword}}" login_user=root state=present

- name: Create MySQL User
  mysql_user: name={{ MySqlDatabaseName }} login_password="{{MySqlRootPassword}}" login_user=root password={{ MySqlDatabasePassword }} priv=typo3.*:ALL state=present

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_password="{{ MySqlRootPassword }}" login_user=root

- name: Secures the MySQL root user
  mysql_user: user="root" password="{{ MySqlRootPassword }}" login_password="{{ MySqlRootPassword }}" login_user=root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ MySqlRootPassword }}" login_user=root
